version: '$(app_version).{build}'
configuration: Release
platform: Any CPU
os: Visual Studio 2015

environment:
  app_version: '2.0.1'
  app_version_postfix: '-beta'

branches:
  except:
    - gh-pages

skip_tags: true
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true

install:
  - SET app_version_informational=%app_version%%app_version_postfix%
  - echo Building Owin.Security.Keycloak Version %app_version_informational% ...

before_build:
  - nuget restore src\KeycloakOwinAuthentication.sln

build:
  project: src\Owin.Security.Keycloak\Owin.Security.Keycloak.csproj
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
cache: src\packages -> src\**\packages.config

matrix:
  fast_finish: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(app_version)"
  assembly_file_version: "{version}"
  assembly_informational_version: "$(app_version_informational)"

deploy:
  - provider: NuGet
    server: 
    api_key:
      secure: jigW/LbSeBUxnQNVrzZqAEDhk9JFMlq5y+00yxi6SwgoQHfFWPUT5tmku3tbp8tz
    skip_symbols: false
    symbol_server: 
    artifact: /.*\.nupkg/
    on:
      branch: master
  - provider: GitHub
    release: v$(app_version_informational)
    description: 'Automated release of Keycloak Owin Authentication version $(app_version_informational) via Appveyor.'
    auth_token:
      secure: dGCvff0hrYX1dStYv8MUNRzuDsaABTOQvMZuhB4dCJ39G0koh9FaAqPf1rIICWy3
    artifact: /.*\.nupkg/
    draft: false
    prerelease: true
    on:
      branch: master
